[package]
name = "deep-sea"
version = "0.1.0"
edition = "2024"

[dependencies]
bit-set = "0.8.0"
googletest = "0.14.0"
itertools = "0.14.0"
lazy_static = "1.5.0"
num = "0.4.3"
rand = "0.9.0"
termion = "4.0.4"
